### ISSUE TITLE
保護名とMCIDを@@で囲む

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/ObserverUtils#60]

**Comment by m2en** [comment]
Redmine へのチケット発行部分を囲えば大丈夫ですか？

https://github.com/GiganticMinecraft/ObserverUtils/blob/69224f26bf0365dbb8c7344d075f2e14d87690e9/src/main/kotlin/click/seichi/observerutils/commands/Command.kt#L62-L84

**Comment by m2en** [comment]
↑ @Lucky3028

**Comment by Lucky3028** [comment]
今気づきました、すみません。そうです！ @mel9y
